# Generated by Django 4.2.5 on 2023-10-31 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertdb',
            old_name='Area',
            new_name='Department',
        ),
    ]
