# Generated by Django 4.2.5 on 2023-10-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_diseasedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reply', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
