# Generated by Django 4.2.5 on 2023-11-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_datasetdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeremedyDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DName', models.CharField(blank=True, max_length=100, null=True)),
                ('HName', models.CharField(blank=True, max_length=100, null=True)),
                ('Remedy', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
