# Generated by Django 3.2.8 on 2023-11-29 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_rename_password_expertdb_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Intraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='expertdb',
            name='CI_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.chat_intraction'),
        ),
    ]
