# Generated by Django 3.2.8 on 2023-11-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_auto_20231129_1203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyDb',
        ),
    ]
