# Generated by Django 4.2.5 on 2023-11-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DName', models.CharField(blank=True, max_length=100, null=True)),
                ('Symptom', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
