# Generated by Django 4.2.5 on 2023-11-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Suggestion', models.CharField(blank=True, max_length=100, null=True)),
                ('Discription', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
