# Generated by Django 4.2.5 on 2023-11-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_logindb_remove_suggestiondb_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindb',
            name='Phone_Number',
        ),
        migrations.RemoveField(
            model_name='logindb',
            name='Pin',
        ),
        migrations.RemoveField(
            model_name='logindb',
            name='Place',
        ),
        migrations.RemoveField(
            model_name='logindb',
            name='Post',
        ),
    ]
