# Generated by Django 4.2.5 on 2023-11-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_remove_logindb_phone_number_remove_logindb_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
