# Generated by Django 4.2.5 on 2023-11-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_userprofile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_db',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Frontend.logindb'),
        ),
    ]
