# Generated by Django 4.2.5 on 2023-11-23 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_userprofile_login_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='login_db',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Frontend.logindb'),
        ),
    ]
