# Generated by Django 4.2.5 on 2023-11-23 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_rename_password_expertdb_password_and_more'),
        ('Frontend', '0008_alter_userprofile_login_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.expertdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Frontend.logindb')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
