# Generated by Django 4.2.5 on 2023-11-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_rename_password_expertdb_password_and_more'),
        ('Frontend', '0009_chatmessage_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_messages', to='Backend.expertdb'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='Frontend.logindb'),
        ),
    ]
