# Generated by Django 3.2.8 on 2023-11-29 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_auto_20231129_1203'),
        ('Frontend', '0011_rename_date_sent_chatmessage_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindb',
            name='CI_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.chat_intraction'),
        ),
    ]
