# Generated by Django 3.2.8 on 2023-11-29 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_auto_20231129_1203'),
        ('Frontend', '0012_logindb_ci_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='fromid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='Backend.chat_intraction'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='toid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='Backend.chat_intraction'),
        ),
    ]
