# Generated by Django 3.2.8 on 2023-11-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0013_auto_20231129_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaindb',
            name='Date',
            field=models.DateField(auto_now_add=True, default='2023-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaindb',
            name='Reply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
