# Generated by Django 3.2.8 on 2023-11-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0014_auto_20231129_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaindb',
            name='Login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontend.logindb'),
        ),
    ]
