# Generated by Django 3.2.8 on 2023-11-29 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0015_complaindb_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestiondb',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
