# Generated by Django 3.2.8 on 2023-11-30 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_auto_20231129_1203'),
        ('Frontend', '0016_suggestiondb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestiondb',
            name='Ex_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.expertdb'),
        ),
    ]
