# Generated by Django 3.2.8 on 2023-11-30 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0017_suggestiondb_ex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestiondb',
            name='Login_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontend.logindb'),
        ),
    ]
